// ! DO NOT CHANGE IT MANUALLY !
// This file is automatically generated
// To change this file, please run "pnpm route'

enum ROUTE_ALIASES_MAP {
  'notFound' = '/pages/404/index',
  'createTask' = '/pages/createTask/index',
  'home' = '/pages/home/index',
  'mine' = '/pages/mine/index',
  'myTask' = '/pages/myTask/index',
  'personalProfileEdit' = '/pages/personalProfileEdit/index',
  'pointMall' = '/pages/pointMall/index',
  'pointRecord' = '/pages/pointRecord/index',
  'task' = '/pages/task/index',
}

export default ROUTE_ALIASES_MAP
