// ! DO NOT CHANGE IT MANUALLY !
// This file is automatically generated
// To change this file, please run "pnpm route'

enum ROUTE_ALIASES_MAP {
  'home' = '/pages/home/index',
  'mine' = '/pages/mine/index',
  'point' = '/pages/point/index',
  'store' = '/pages/store/index',
  'task' = '/pages/task/index',
}

export default ROUTE_ALIASES_MAP
