// ! DO NOT CHANGE IT MANUALLY !
// This file is automatically generated
// To change this file, please run "pnpm route'

/** 跳转路由参数 */
export default interface RouterParams {
  notFound: Record<string, never>
  createTask: Record<string, never>
  home: Record<string, never>
  mine: Record<string, never>
  myTask: Record<string, never>
  personalProfileEdit: Record<string, never>
  point: Record<string, never>
  store: Record<string, never>
  task: { task_id?: any }
}
