// ! DO NOT CHANGE IT MANUALLY !
// This file is automatically generated
// To change this file, please run "pnpm route'

/** 跳转路由参数 */
export default interface RouterParams {
  home: Record<string, never>
  mine: Record<string, never>
  point: Record<string, never>
  store: Record<string, never>
  task: { task_id?: any }
}
