// DO NOT CHANGE IT MANUALLY!
// This file is automatically generated
// To change this file, please run "pnpm route'

export enum ROUTE {
  'home' = 'home',
  'mine' = 'mine',
  'point' = 'point',
  'store' = 'store',
  'task' = 'task',
}

export default interface RouterParams extends Record<ROUTE, any> {
  [ROUTE.home]: {}
  [ROUTE.mine]: {}
  [ROUTE.point]: {}
  [ROUTE.store]: {}
  [ROUTE.task]: { task_id: any }
}
