// DO NOT CHANGE IT MANUALLY!
// This file is automatically generated
// To change this file, please run "pnpm route'

enum PATH_TO_ALIASES_MAP {
  '/pages/home/index' = 'home',
  'pages/home/index' = 'home',
  '/pages/mine/index' = 'mine',
  'pages/mine/index' = 'mine',
  '/pages/point/index' = 'point',
  'pages/point/index' = 'point',
  '/pages/store/index' = 'store',
  'pages/store/index' = 'store',
  '/pages/task/index' = 'task',
  'pages/task/index' = 'task',
}

export default PATH_TO_ALIASES_MAP
