export const headerStatement = `
// ! DO NOT CHANGE IT MANUALLY !
// This file is automatically generated
// To change this file, please run "pnpm route'

`

export const chunkStatement = `
// ! DO NOT CHANGE THE CODE CHUNK MANUALLY !
// This code chunk is automatically generated
// To change this code chunk, please run "pnpm route"

`
